# Configuration for Ten Week Goal App


[storage]
# Relative paths from project root
# Updated to use the shared database with existing data
data_dir = "../shared/database"
db_name = "application_data.db"
schema_dir = "../shared/schemas"

[logging]
level = "INFO"
log_dir = "logs"
